tasks

diff --git a/.github/workflows/team_a_1.yml b/.github/workflows/team_a_1.yml
--- a/.github/workflows/team_a_1.yml
+++ b/.github/workflows/team_a_1.yml
@@ -22,6 +22,16 @@ jobs:
           java-version: 21
           distribution: 'temurin'
           cache: gradle
+      - name: Check if java is available
+        shell: bash
+        run: |
+          if ! command -v java &> /dev/null
+          then
+            echo "java could not be found"
+            exit 1
+          else
+            echo "java is available"
+          fi
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
       - name: Build with Tests
